### ISSUE TITLE
develop -> main merges do not trigger a release

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/opensource-website#797] opened 2021-06-09 21:53 UTC
## Description
Merges from develop to main do not trigger a new build in Amplify. We are unsure of why this is happening because the `project-stats` workflow triggers a release of `main` without an issue.
* Review docs after investigating this issue and make any needed updates

 
**Workaround**: Wait for the `project-stats` workflow to run and trigger a release.

### Possibly related things
The `project-stats` workflow commits directly to `develop` and cherry picks the commit to `main`. This is still working correctly, however it's worth noting that the main branch is considered to be over 2000 commits ahead of main.

### Acceptance Criteria 

- [ ] Confirm with @jbeveland27 if there was a specific reason this approach was taken for `project-stats`
- [ ] Implement option 3

```dont make project stats commits to develop. its those commits (and their frequency) that mainly contribute to this problem. it seems like we dont need to make them to develop since we make them to main anyways. if we went with this option, it kind of overlaps with solution 2 (and simplifies things), since we dont need to merge periodically, only when changes are introduced. additionally, there is another benefit we gain in that prs from develop -> main will be easier to review -- since there will be less changes in the PR.```

**Comment by aswanson-nr** [comment] 2021-06-09 21:54
@jbeveland27 Could you take a look when you have a chance?

**Comment by jbeveland27** [comment] 2021-06-09 22:19
@aswanson-nr Not sure what's up. FWIW I can trigger a build using the `triggermain` webhook in `Build Settings` on AWS.

There's a `reconnect repository` button in the Amplify Console that will set up a new webhook from this repo to Amplify. I can do that if you'd like?

![image](https://user-images.githubusercontent.com/6722433/121436695-0cd7ca00-c94f-11eb-87a5-a650bf1b916a.png)

**Comment by aswanson-nr** [comment] 2021-06-10 16:23
I thought it might be something related to those webhooks, but they appear to have only been used by this workflow https://github.com/newrelic/opensource-website/blob/develop/.github/workflows/project-stats.yml#L133-L159, which has been commented out for some time now. The integration seems to be what handles build and I'm leaning toward disconnected and reconnecting it as well. I can tackle it! I'd like to look into why `main` is so far ahead of `develop` before making any changes.

**Comment by jbeveland27** [comment] 2021-06-11 15:02
`main` is ahead of `develop` by design (for better or worse). It's because the stats sync - commits are made to `develop` and then [cherry-picked](https://github.com/newrelic/opensource-website/blob/develop/.github/workflows/project-stats.yml#L60-L69) from `develop` to `main`, which creates a new commit in `main` that doesn't exist in `develop`. 

The important thing I tried to keep track of is when `main` is _behind_ `develop` (which is easy to see in the GitHub UI), there are changes in stage that are pending release to production. Once `main` is no longer behind `develop`, you know staging and production are in sync.

![image](https://user-images.githubusercontent.com/6722433/121707416-86cd9780-caa4-11eb-8879-366129eee029.png)

**Comment by nr-kkenney** [comment] 2021-06-22 00:11
yea i think the awkward thing, or maybe something that isn't immediately obvious at first (at least to me), is that main can be both ahead & behind develop with the cherry-pick commits, even though we know the commits contain the same content change, and a pr from develop -> main looks large because of this, even though it should be empty since all file content should be identical.

**Comment by nr-kkenney** [comment] 2021-06-22 20:55
i think i got to the bottom of this. tl;dr - the merges that failed to trigger a build were due to the size of the payload being sent on the amplify webhook. the request body contains the commits & changed files, so the more commits we let sit in develop w/o merging to main, the larger the request body we will next send. commits directly to main dont run into this problem because they are single commits, so that explains why prs run into this problem, but commits do not.

not every merge to main will run into the problem. in fact, i was able to get a pr to trigger a release, but it included only 1 commit (the project stats commit). as mentioned above, the longer the period between merges, the larger the subsequent request will be, and we will run into the limit.

possible next steps:
1. do nothing. this actually isn't that big of a problem, since a release will be triggered when the next project stats commit gets merged (every 4 hours).
2. improve our process, merge more frequently. if we merged more frequently, we might not run into this problem anymore. i dont know what the frequency would need to be, but i was able to get a pr merge to trigger a build with only one project stats commit.
3. dont make project stats commits to develop. its those commits (and their frequency) that mainly contribute to this problem. it seems like we dont need to make them to develop since we make them to main anyways. additionally, there is another benefit we gain in that prs from develop -> main will be easier to review -- since there will be less changes to review.

screenshots:
![Screen Shot 2021-06-22 at 1 28 35 PM](https://user-images.githubusercontent.com/70179215/122996671-fd4d7d80-d35f-11eb-8f50-96fafb4af74a.png)
![Screen Shot 2021-06-22 at 1 45 35 PM](https://user-images.githubusercontent.com/70179215/122996971-5cab8d80-d360-11eb-859d-6593fae0f329.png)

@jpvajda @zstix @aswanson-nr

**Comment by nr-kkenney** [comment] 2021-06-22 21:26
update: 
doesn't change the outcome, but i think @roadlittledawn had a better understanding / educated guess to the problem when I spoke to him. in the image above, the response contains `Request-URI Too Large`, so some internal aws resource is running into a limit of some kind. as a slight tangent, but related, in our interactions with smartling, file paths are part of the request URI as query params, so he was thinking it could be something like that versus just the payload being too large, and i think that makes more sense. 

so the part where i say the payload is too large is probably incorrect 🙈 .

**Comment by jpvajda** [comment] 2021-06-22 21:57
FWIW: whatever the root issue is: I like `2` that you laid out: 

```improve our process, merge more frequently. if we merged more frequently, we might not run into this problem anymore. i dont know what the frequency would need to be, but i was able to get a pr merge to trigger a build with only one project stats commit.```

It could nice to just to merge the project stats in automatically like once every 72 hours or something, and have a PR from develop to main that just contains the project stat changes only.

**Comment by zstix** [comment] 2021-06-23 16:48
After discussing this, we decided to move forward with option 3.

**Closed** 2021-06-24 17:11 UTC
Labels: P2, bug, gatsbysites, hero, sp:3
